(load "../library/vector.scm")

(define (bubble-sort! vec less?)
  (let ((vc (- (vector-length vec) 1)))
    (for-each (lambda (i)
      (for-each (lambda (j)
        (let ((x (vector-ref vec j))
              (y (vector-ref vec (+ j 1))))
          (if (not (less? x y))
            (vector-swap! vec j (+ j 1)))))
      (iota (- vc i))))
    (iota vc))))
